package com.casla.eclipse.ai.completion;

import java.util.List;

import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.OperationCanceledException;
import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.ui.text.java.ContentAssistInvocationContext;
import org.eclipse.jdt.ui.text.java.IJavaCompletionProposalComputer;
import org.eclipse.jdt.ui.text.java.JavaContentAssistInvocationContext;
import org.eclipse.jface.text.IDocument;
import org.eclipse.jface.text.contentassist.CompletionProposal;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.jface.text.contentassist.IContextInformation;

import com.casla.eclipse.ai.api.RuntimeSnapshot;
import com.casla.eclipse.ai.client.ApiException;
import com.casla.eclipse.ai.client.CompletionResponse;
import com.casla.eclipse.ai.preferences.AiPreferences;
import com.casla.eclipse.ai.runtime.AiRuntime;

public final class AiCompletionProposalComputer implements IJavaCompletionProposalComputer {
    private volatile String errorMessage;

    @Override
    public List<ICompletionProposal> computeCompletionProposals(
        ContentAssistInvocationContext invocation,
        IProgressMonitor monitor
    ) {
        RuntimeSnapshot runtime = AiRuntime.get().snapshot();
        if (!runtime.canComplete() || !(invocation instanceof JavaContentAssistInvocationContext javaContext)) {
            return List.of();
        }

        IDocument document = javaContext.getViewer().getDocument();
        ICompilationUnit compilationUnit = javaContext.getCompilationUnit();
        try {
            CodeContext context = new ContextExtractor().extract(
                compilationUnit,
                document,
                javaContext.getInvocationOffset(),
                new AiPreferences().completionSettings()
            );
            CompletionResponse response = AiRuntime.get().complete(context, monitor);
            if (!context.isCurrent(document)) return List.of();

            // Already sanitized (and confirmed non-blank) by AiRuntime.complete().
            String insertion = response.content();

            errorMessage = null;
            String display = "AI suggestion · " + runtime.resolvedModelId();
            ICompletionProposal proposal = new CompletionProposal(
                insertion,
                context.cursorOffset(),
                0,
                insertion.length(),
                null,
                display,
                null,
                "Generated by " + response.responseModel()
            );
            return List.of(proposal);
        } catch (OperationCanceledException ignored) {
            return List.of();
        } catch (ApiException error) {
            errorMessage = error.getMessage();
            return List.of();
        } catch (Exception error) {
            errorMessage = "Could not prepare the Java completion context.";
            return List.of();
        }
    }

    @Override
    public List<IContextInformation> computeContextInformation(
        ContentAssistInvocationContext context,
        IProgressMonitor monitor
    ) {
        return List.of();
    }

    @Override
    public String getErrorMessage() {
        return errorMessage;
    }

    @Override
    public void sessionStarted() {
        errorMessage = null;
    }

    @Override
    public void sessionEnded() {
        // No session-scoped resources.
    }
}
